const nameList = [
  "Aarav",         
  "Fatima",        
  "Kabir",         
  "Simran",        
  "Aditya",        
  "Ayesha",        
  "Rahul",         
  "Mary",          
  "Ishaan",        
  "Harpreet",      
  "Yusuf",        
  "Sneha",       
  "Rehan",         
  "Tanya",        
  "Nirav",        
  "Aalia",         
  "David",         
  "Avani",         
  "Rohan",         
  "Gurleen",       
  "Farhan",        
  "Riya",          
  "Samar",         
  "Angel",         
  "Aryan",         
  "Zoya",          
  "Cyrus",         
  "Nikita",        
  "Haroon",        
  "Manpreet",      
  "Vivaan",        
  "Anam",          
  "Kunal",         
  "Rebecca",       
  "Omar",          
  "Pooja",         
  "Tenzin",        
  "Parveen",       
  "Meera",         
  "Ashwin"         
]


export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

const messageList = [
  "Let's goooo!!! 🔥",
  "Who's watching in 2025?",
  "Chat's going crazy 😂",
  "This part is legendary!",
  "Can we get some hype in the chat?",
  "Don’t forget to like the stream!",
  "W spam in the chat!!",
  "LMAO 😂😂😂",
  "That was insane!!",
  "Mod check 👀",
  "Stream lagging or just me?",
  "No way that just happened 😱",
  "F in the chat...",
  "Song name??",
  "W stream fr 🔥",
  "He actually did it 😭",
  "Sub if you're new!",
  "I'm crying 😂",
  "They’re goated 🔥",
  "Here before 1M views!",
  "This chat is wild lol",
  "Can we get a like spike?",
  "I’m watching from India 🇮🇳",
  "First time here, love the vibe!",
  "Yo this beat is fire 🔥",
  "POV: You're vibing with chat rn",
  "This is peak content 💯",
  "Please notice me 😭",
  "Who else watching at 3am?",
  "That transition tho 🤯",
  "W mods 🛡️",
  "Bro really said 💀",
  "I've been waiting for this all day!",
  "Mic muted??",
  "This energy is unmatched 🔥",
  "Replay gang where you at?",
  "That edit was clean!",
  "Respect to the grind 🙌",
  "GGs in the chat!",
  "Y’all see that?? 😳"
]

export function generateRandomMessage(length) {
return messageList[Math.floor(Math.random() * messageList.length)];
}